### ISSUE TITLE
Start building JS - xhr requests

### ISSUE THREAD

**Issue by SavageWilliam** [FAC9/repos_api_website#3]
- Determine paths in API- hence URLs and url constructors. 
- build basic request function

-DONT worry about DOM manipulations yet (later)

**Comment by emilyb7** [comment]
## Get list of movies

Link to get all movies: https://api.themoviedb.org/3/discover/movie?api_key=***&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=true&page=1

To get the number of pages return "total_pages" from the JSON response

There are 10 results on a page. In order to get a random result we need to generate a random page number (e.g. between 1 and 14855) and then generate a random number from 0-9 in order to get a result from the random page.

## Filter by genre

To get a specific genre add `&with_genres=` to the ID

Genres are identified by their ID. Here are some IDs we will need:

Comedy: 35
Action: 28
Romance: 10749
Thriller: 53
Family: 10751

## Filter by release year

Get film from this year: we would need to get the current year using the JS date object and add to the URL: `&primary_release_year=YEAR`

To get all films from a certain decade, e.g. the 2000s: `&primary_release_date.lte=2010-01-01&primary_release_date.gte=2000-01-01``

## Films by length

To get films by length: To get films under 60 mins: `&with_runtime.lte=60`
